@echo off
echo Starting COE Exam Cell Portal...
echo.
echo [1] Checking dependencies...
if not exist node_modules (
    echo Dependencies not found. Installing...
    call npm install
)
echo [2] Starting local server...
start "" http://localhost:5173
call npm run dev
pause
